version: '3'

services:
    php:
      image: custom_php:latest
      build:
        context: ./php
      container_name: ${COMPOSE_PROJECT_NAME}_php
      expose:
        - 9000
      volumes:
        - ./..:/var/www/html
      depends_on:
        - mysql
      environment:
        # default config to enable xdebug
        XDEBUG_CONFIG: "client_host=172.17.0.1"
        PHP_IDE_CONFIG: "serverName=phpServer"
    mysql:
      image: mysql:8.0
      container_name: ${COMPOSE_PROJECT_NAME}_mysql
      command: --default-authentication-plugin=mysql_native_password
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=database_name
      ports:
        - "33061:3306"
      volumes:
        - ./mysql/data:/var/lib/mysql

